### PR TITLE
Docstore comment permissions

### PR DESCRIPTION
**Pull request by megan-dove**
Please review my last commit (fe609f9b50ef5c52e351c0730841a55ede74b26a).
Everything else has already been reviewed by Jenny. The branch will not be merged in until everything Rachel did has been tested again as there as some [known issues with this for UEA](https://cayuse.atlassian.net/browse/PHDM-1247?search_id=e8019394-f96b-401f-bc80-2e3c1794f870).

The issue:
When 'show comments', 'show changes' AND 'filter questions' are selected in the document view, any questions within containers (e.g. questions within repeating sections, file uploads) that have a comment but NO changes, were not showing.

This was happening because the container is not visible due to not having any changes and the code that should make elements with comments visible was only setting the actual element as visible and not the container.

The fix:
Check if all elements, including containers, should be visible.

I am not convinced that there is any need to check whether an element is a container or not as I can't see that this is doing anything. I have left the code in just in case however.

Please let me know if you would like a demo of this.
Dev system: https://dev7a17.infomanaged.co.uk
I have also tested this in a couple of other dev systems for other clients. I think it would be worth you doing the same to make sure this doesn't break anything.

### CODE REVIEW

**Comment by megan-dove** [comment]
Please let me know if you would like a demo of this.

**Review by NJx-786 — COMMENTED** [review]
Checked code and demo was produced.

**Review by jderoberts — COMMENTED** [review]
The additional comments.js change to fix comment filtering for repeating sections looks good+as demoed

**Comment by megan-dove** [comment]
@jderoberts please review the latest commit.
I have put a change made by Rachel previously on this branch (https://github.com/haplo-org/haplo-standard-plugins-dev/commit/82be3b8193c4caa51997ad0771fb1c6a36ccf00f) behind a config.

Linked code review: https://developers.infomanaged.co.uk/81q85/uea-comments-revisions

You can use the same test environment.

**Pull request merged**
